services:
  - type: web
    name: miguel-n8n-keepalive-orchestrator
    env: node
    plan: free
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"
    healthCheckPath: "/healthz"
    envVars:
      # Postgres (Neon)
      - key: DB_POSTGRESDB_HOST
        value: "ep-plain-fire-acfan4ne-pooler.sa-east-1.aws.neon.tech"
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_USER
        value: "neondb_owner"
      - key: DB_POSTGRESDB_PASSWORD
        sync: false
      - key: DB_POSTGRESDB_DATABASE
        value: "neondb"
      - key: DB_POSTGRESDB_SSL_MODE
        value: "require"
      - key: DB_POSTGRESDB_SSL_CA
        sync: false   # cole aqui o PEM se quiser validar CA

      # Segurança do app (opcional)
      - key: GENERIC_TIMEZONE
        value: "America/Sao_Paulo"

    # Se quiser persistência local por algum motivo, adicione disk; para Neon não é necessário
    # disk:
    #   name: data
    #   mountPath: /data
    #   sizeGB: 0.3

