services:
  - type: web
    name: n8n3-keepalive
    env: node
    plan: free
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"
    disk:
      name: persistente
      mountPath: /data
      sizeGB: 1
